/**
 * Maps ISO 3166-1 alpha-3 nationality codes to their country's capital city.
 * Also supports common English country name variants for OCR fallback matching.
 */
const CAPITALS_BY_CODE: Record<string, string> = {
  // Asia-Pacific
  JPN: 'Tokyo',
  VNM: 'Hanoi',
  CHN: 'Beijing',
  KOR: 'Seoul',
  TWN: 'Taipei',
  THA: 'Bangkok',
  SGP: 'Singapore',
  MYS: 'Kuala Lumpur',
  PHL: 'Manila',
  IDN: 'Jakarta',
  IND: 'New Delhi',
  AUS: 'Canberra',
  NZL: 'Wellington',
  HKG: 'Hong Kong',
  MAC: 'Macao',
  MMR: 'Naypyidaw',
  KHM: 'Phnom Penh',
  LAO: 'Vientiane',
  BRN: 'Bandar Seri Begawan',
  TLS: 'Dili',
  NPL: 'Kathmandu',
  BGD: 'Dhaka',
  LKA: 'Sri Jayawardenepura Kotte',
  PAK: 'Islamabad',
  AFG: 'Kabul',
  IRN: 'Tehran',
  IRQ: 'Baghdad',
  // Americas
  USA: 'Washington D.C.',
  CAN: 'Ottawa',
  MEX: 'Mexico City',
  BRA: 'Brasilia',
  ARG: 'Buenos Aires',
  CHL: 'Santiago',
  COL: 'Bogota',
  PER: 'Lima',
  VEN: 'Caracas',
  ECU: 'Quito',
  BOL: 'Sucre',
  PRY: 'Asuncion',
  URY: 'Montevideo',
  // Europe
  GBR: 'London',
  FRA: 'Paris',
  DEU: 'Berlin',
  ITA: 'Rome',
  ESP: 'Madrid',
  PRT: 'Lisbon',
  NLD: 'Amsterdam',
  BEL: 'Brussels',
  CHE: 'Bern',
  AUT: 'Vienna',
  SWE: 'Stockholm',
  NOR: 'Oslo',
  DNK: 'Copenhagen',
  FIN: 'Helsinki',
  POL: 'Warsaw',
  RUS: 'Moscow',
  UKR: 'Kyiv',
  CZE: 'Prague',
  SVK: 'Bratislava',
  HUN: 'Budapest',
  ROU: 'Bucharest',
  BGR: 'Sofia',
  SRB: 'Belgrade',
  HRV: 'Zagreb',
  GRC: 'Athens',
  TUR: 'Ankara',
  // Middle East & Africa
  SAU: 'Riyadh',
  ARE: 'Abu Dhabi',
  QAT: 'Doha',
  KWT: 'Kuwait City',
  BHR: 'Manama',
  OMN: 'Muscat',
  ISR: 'Jerusalem',
  JOR: 'Amman',
  LBN: 'Beirut',
  EGY: 'Cairo',
  ZAF: 'Pretoria',
  NGA: 'Abuja',
  KEN: 'Nairobi',
  ETH: 'Addis Ababa',
  GHA: 'Accra',
  TZA: 'Dodoma',
  UGA: 'Kampala',
};

// Map common full country name variants (uppercase) to ISO codes
const NAME_TO_CODE: Record<string, string> = {
  JAPAN: 'JPN',
  VIETNAM: 'VNM',
  'VIET NAM': 'VNM',
  CHINA: 'CHN',
  'SOUTH KOREA': 'KOR',
  KOREA: 'KOR',
  TAIWAN: 'TWN',
  THAILAND: 'THA',
  SINGAPORE: 'SGP',
  MALAYSIA: 'MYS',
  PHILIPPINES: 'PHL',
  INDONESIA: 'IDN',
  INDIA: 'IND',
  AUSTRALIA: 'AUS',
  'NEW ZEALAND': 'NZL',
  'HONG KONG': 'HKG',
  MYANMAR: 'MMR',
  CAMBODIA: 'KHM',
  LAOS: 'LAO',
  NEPAL: 'NPL',
  BANGLADESH: 'BGD',
  'SRI LANKA': 'LKA',
  PAKISTAN: 'PAK',
  IRAN: 'IRN',
  USA: 'USA',
  'UNITED STATES': 'USA',
  'UNITED STATES OF AMERICA': 'USA',
  CANADA: 'CAN',
  MEXICO: 'MEX',
  BRAZIL: 'BRA',
  ARGENTINA: 'ARG',
  'UNITED KINGDOM': 'GBR',
  UK: 'GBR',
  ENGLAND: 'GBR',
  FRANCE: 'FRA',
  GERMANY: 'DEU',
  ITALY: 'ITA',
  SPAIN: 'ESP',
  PORTUGAL: 'PRT',
  NETHERLANDS: 'NLD',
  BELGIUM: 'BEL',
  SWITZERLAND: 'CHE',
  AUSTRIA: 'AUT',
  SWEDEN: 'SWE',
  NORWAY: 'NOR',
  DENMARK: 'DNK',
  FINLAND: 'FIN',
  POLAND: 'POL',
  RUSSIA: 'RUS',
  UKRAINE: 'UKR',
  TURKEY: 'TUR',
  'SAUDI ARABIA': 'SAU',
  UAE: 'ARE',
  'UNITED ARAB EMIRATES': 'ARE',
  EGYPT: 'EGY',
  'SOUTH AFRICA': 'ZAF',
};

/**
 * Returns the capital city for a given nationality string.
 * Accepts ISO alpha-3 codes (e.g. "JPN") or common country name variants (e.g. "Japan").
 * Returns empty string if no match found.
 */
export function getCountryCapital(nationality: string): string {
  if (!nationality) return '';
  const upper = nationality.toUpperCase().trim();
  // Try ISO 3-letter code first
  if (CAPITALS_BY_CODE[upper]) return CAPITALS_BY_CODE[upper];
  // Try full name lookup
  const code = NAME_TO_CODE[upper];
  if (code && CAPITALS_BY_CODE[code]) return CAPITALS_BY_CODE[code];
  return '';
}
